# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [2]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [7]:
np.version.version

'1.19.2'

#### Q3 : Créer un vecteur nul de taille 10

In [69]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [71]:
m = np.zeros(10)
m[4] = 1
m

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [27]:
np.arange(10,50,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [26]:
mz = np.arange(10,50,1)
mz[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [33]:
m3 = np.arange(9).reshape(3,3);
m3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3 

In [53]:
np.eye(3, 3, 0)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [74]:
m = np.random.randint(10, size=(3,3,3))
print(m)
m = np.random.rand(3,3,3)
print(m)

[[[3 2 3]
  [1 1 6]
  [0 1 0]]

 [[9 4 8]
  [8 0 7]
  [4 3 8]]

 [[4 9 1]
  [2 2 0]
  [2 8 1]]]
[[[0.13667774 0.09966517 0.77397125]
  [0.53988545 0.97543556 0.63456812]
  [0.95037455 0.55089457 0.93382919]]

 [[0.96999833 0.00357126 0.23373699]
  [0.10877029 0.48577332 0.05266446]
  [0.17523527 0.9732747  0.67612119]]

 [[0.53083933 0.08292186 0.03160468]
  [0.06721173 0.13951132 0.33645079]
  [0.94267944 0.5493999  0.55388377]]]


#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [46]:
m = np.random.randint(10, size=(3,3))
print(m)
m.min(), m.max()

[[7 3 5]
 [4 7 3]
 [8 8 3]]


(3, 8)

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [57]:
np.diag(np.array([1,2,3,4]),-1)# à faire

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [66]:
m = np.random.randint(0,10, 5)
print(m)
m.sum()

[5 4 1 3 3]


16

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [67]:
m.mean()

3.2

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [137]:
l = [x for x in range(11)]
np.size(l)

11

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [142]:
# m = np.random.ranf(4)
# m
m = np.linspace(0,1,11,False)[1:]
print(m)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [148]:
A = np.random.ranf(5)
print(A)
B = np.random.ranf(5)
print(B)
np.array_equal(A,B)
np.array_equal(A,A)


[0.37912518 0.76537152 0.97635717 0.57893275 0.10585976]
[0.23478857 0.11173504 0.63623676 0.87648204 0.47222147]


True

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [149]:
# m = np.random.ranf(10)
m = np.random.randint(0,10, 10)
print(m.dtype)
m = np.float32(m)
print(m)
m = np.int32(m)
print(m)

int64
[3. 4. 2. 3. 4. 9. 9. 1. 1. 7.]
[3 4 2 3 4 9 9 1 1 7]


#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

In [164]:
z = np.random.randint(0,10, 10)
z=(z - np.mean (z)) / (np.std(z))
z

array([ 0. , -1. , -0.5,  2. , -1.5,  0. ,  0.5,  1. ,  0.5, -1. ])

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

In [153]:
m = np.random.randint(10, size=(2,2))
print(m)
np.transpose(m)

[[1 0]
 [4 7]]


array([[1, 4],
       [0, 7]])

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

In [193]:
def randReplace(m):
    # print(len(m), len(m[0]))
    print(m)
    x=np.random.randint(0,len(m[0]))
    y=np.random.randint(0,len(m))
    m[y][x] = 11
    print("******")
    print(m)


m = np.random.randint(10, size=(2,3))
randReplace(m)




[[7 7 1]
 [1 7 8]]
******
[[ 7  7 11]
 [ 1  7  8]]


#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)

In [190]:
a = np.random.randint(10, size=(5,5,3))
b = np.random.randint(10, size=(5,5))
print(b)
print("*******************")
print(np.transpose(np.array([b,])))
print("*******************")
print(np.transpose(np.array([b,]*len(a[0][0]))))
print("*******************")
print (a * np.transpose(np.array([b,]*len(a[0][0]))))

[[0 9 9 4 7]
 [2 9 4 3 6]
 [6 9 9 9 3]
 [0 8 8 3 5]
 [3 8 9 5 1]]
*******************
[[[0]
  [2]
  [6]
  [0]
  [3]]

 [[9]
  [9]
  [9]
  [8]
  [8]]

 [[9]
  [4]
  [9]
  [8]
  [9]]

 [[4]
  [3]
  [9]
  [3]
  [5]]

 [[7]
  [6]
  [3]
  [5]
  [1]]]
*******************
[[[0 0 0]
  [2 2 2]
  [6 6 6]
  [0 0 0]
  [3 3 3]]

 [[9 9 9]
  [9 9 9]
  [9 9 9]
  [8 8 8]
  [8 8 8]]

 [[9 9 9]
  [4 4 4]
  [9 9 9]
  [8 8 8]
  [9 9 9]]

 [[4 4 4]
  [3 3 3]
  [9 9 9]
  [3 3 3]
  [5 5 5]]

 [[7 7 7]
  [6 6 6]
  [3 3 3]
  [5 5 5]
  [1 1 1]]]
*******************
[[[ 0  0  0]
  [12  4 10]
  [18 12 12]
  [ 0  0  0]
  [ 0 24 24]]

 [[27 36 54]
  [ 9 72 72]
  [54 72  0]
  [48 64 64]
  [ 0 40  0]]

 [[27  0 63]
  [ 0 16 12]
  [ 0 63 72]
  [64 32 24]
  [27 45  0]]

 [[ 0 12  0]
  [ 9 27 27]
  [45 27 18]
  [ 3 12  3]
  [45 20 25]]

 [[49 63 35]
  [54 18 30]
  [15  3 15]
  [10 40 45]
  [ 7  0  6]]]
